[package]
name = "datadog_agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[test]]
name = "scheduler_integration_tests"
path = "tests/scheduler_integration_tests.rs"
